select distinct ( CASE 
        WHEN tinh_trang_san_pham LIKE '%hết hạn%' 
          OR hsd_con_lai_thang < 0 THEN 'Hết hạn'
        WHEN tinh_trang_san_pham LIKE '%đã qua sử dụng%' 
          OR tinh_trang_san_pham LIKE '%ko có barcode%' 
          OR tinh_trang_san_pham LIKE '%ko có seal%' 
          OR tinh_trang_san_pham LIKE '%mất seal%'
          OR tinh_trang_san_pham LIKE '%không có in date%'
          OR tinh_trang_san_pham LIKE '%mờ date%'
          OR tinh_trang_san_pham LIKE '%cận date%'
          OR tinh_trang_san_pham LIKE '%khui seal%'
          OR tinh_trang_san_pham LIKE '%CTKM hết thời hạn%' THEN 'Hàng hư hỏng'
        WHEN tinh_trang_san_pham LIKE '%bị lỗi%' 
          OR tinh_trang_san_pham LIKE '%bể ô phấn%' 
          OR tinh_trang_san_pham LIKE '%không đủ số lượng%' THEN 'Hàng lỗi'
        WHEN tinh_trang_san_pham LIKE '%cấn móp%' 
          OR tinh_trang_san_pham LIKE '%bạc màu%' 
          OR tinh_trang_san_pham LIKE '%dơ%' 
          OR tinh_trang_san_pham LIKE '%rách hộp%'
          OR tinh_trang_san_pham LIKE '%rách bao bì%' THEN 'Hàng lỗi ngoại quan'
        WHEN tinh_trang_san_pham = 'sản phẩm nguyên vẹn' THEN 'Hàng nguyên vẹn'
        ELSE 'Chưa phân loại' 
    END 
    ) as 'Phân loại'
from thu_hoi_boxme
where {filters}